/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedExportsRouteImport } from './routes/_authed/exports'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiSignupRouteImport } from './routes/api/signup'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks.index'
import { Route as AuthedTasksNewRouteImport } from './routes/_authed/tasks.new'
import { Route as AuthedTasksTaskIdIndexRouteImport } from './routes/_authed/tasks.$taskId.index'
import { Route as AuthedTasksTaskIdEditRouteImport } from './routes/_authed/tasks.$taskId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportsRoute = AuthedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupRoute = ApiSignupRouteImport.update({
  id: '/api/signup',
  path: '/api/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdIndexRoute = AuthedTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdEditRoute = AuthedTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/exports': typeof AuthedExportsRoute
  '/import': typeof AuthedImportRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/tasks': typeof ApiTasksRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/exports': typeof AuthedExportsRoute
  '/import': typeof AuthedImportRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/tasks': typeof ApiTasksRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/exports': typeof AuthedExportsRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/tasks': typeof ApiTasksRoute
  '/_authed/tasks/new': typeof AuthedTasksNewRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/_authed/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/exports'
    | '/import'
    | '/reports'
    | '/settings'
    | '/api/health'
    | '/api/login'
    | '/api/signup'
    | '/api/tasks'
    | '/tasks/new'
    | '/tasks/'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/exports'
    | '/import'
    | '/reports'
    | '/settings'
    | '/api/health'
    | '/api/login'
    | '/api/signup'
    | '/api/tasks'
    | '/tasks/new'
    | '/tasks'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/activity'
    | '/_authed/exports'
    | '/_authed/import'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/api/health'
    | '/api/login'
    | '/api/signup'
    | '/api/tasks'
    | '/_authed/tasks/new'
    | '/_authed/tasks/'
    | '/_authed/tasks/$taskId/edit'
    | '/_authed/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiSignupRoute: typeof ApiSignupRoute
  ApiTasksRoute: typeof ApiTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exports': {
      id: '/_authed/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthedExportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup': {
      id: '/api/signup'
      path: '/api/signup'
      fullPath: '/api/signup'
      preLoaderRoute: typeof ApiSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/new': {
      id: '/_authed/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthedTasksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/': {
      id: '/_authed/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/edit': {
      id: '/_authed/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthedTasksTaskIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedExportsRoute: typeof AuthedExportsRoute
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedTasksTaskIdEditRoute: typeof AuthedTasksTaskIdEditRoute
  AuthedTasksTaskIdIndexRoute: typeof AuthedTasksTaskIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedExportsRoute: AuthedExportsRoute,
  AuthedImportRoute: AuthedImportRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedTasksTaskIdEditRoute: AuthedTasksTaskIdEditRoute,
  AuthedTasksTaskIdIndexRoute: AuthedTasksTaskIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiSignupRoute: ApiSignupRoute,
  ApiTasksRoute: ApiTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
